test_FixedThreadPool:test_FixedThreadPool.cpp ../Thread.cpp ../FixedThreadPool.cpp
	g++ test_FixedThreadPool.cpp ../Thread.cpp ../FixedThreadPool.cpp ../mutex.cpp -lpthread -g -o test_FixedThreadPool
